"""High-level orchestration for the docking preparation workflow."""

from dataclasses import dataclass
from typing import Any, Dict, Optional, Tuple

from ...storage.file_manager import list_files_in_directory
from .steps import (
	ActiveSiteDetection,
	DockingAnalysis,
	DockingExecution,
	LigandPreparation,
	ReceptorPreparation,
)


@dataclass
class DockingPipelineResult:
	"""Structured result for the preparation pipeline."""

	receptor_preparation: Dict[str, int]
	ligand_preparation: Dict[str, int]
	active_site_detection: Dict[str, int]
	docking_execution: Optional[Dict[str, Any]] = None
	docking_analysis: Optional[Dict[str, Any]] = None


class DockingPipeline:
	"""Compose receptor preparation, ligand preparation, and active-site detection.

	This pipeline supports both preparation-only execution and full docking runs
	that include execution and analysis stages.
	"""

	def __init__(
		self,
		receptor_input_path: str,
		ligand_input_path: str,
		output_path: str,
		mgltools_path: Optional[str] = None,
		fpocket_path: Optional[str] = None,
		manual_center: Optional[Tuple[float, float, float]] = None,
		manual_npts: Optional[Tuple[int, int, int]] = None,
	):
		self.receptor_input_path = receptor_input_path
		self.ligand_input_path = ligand_input_path
		self.output_path = output_path
		self.mgltools_path = mgltools_path
		self.fpocket_path = fpocket_path
		self.manual_center = manual_center
		self.manual_npts = manual_npts

	@property
	def prepared_receptor_path(self) -> str:
		"""Return the output directory used by receptor preparation."""
		return f"{self.output_path}/prepared_receptors_pdbqt"

	@property
	def prepared_ligand_path(self) -> str:
		"""Return the output directory used by ligand preparation."""
		return f"{self.output_path}/prepared_ligands_pdbqt"

	def _build_receptor_preparation(self) -> ReceptorPreparation:
		return ReceptorPreparation(
			input_path=self.receptor_input_path,
			output_path=self.output_path,
			mgltools_path=self.mgltools_path,
		)

	def _build_ligand_preparation(self) -> LigandPreparation:
		return LigandPreparation(
			input_path=self.ligand_input_path,
			output_path=self.output_path,
		)

	def _build_active_site_detection(self) -> ActiveSiteDetection:
		return ActiveSiteDetection(
			receptor_path=self.prepared_receptor_path,
			ligand_path=self.prepared_ligand_path,
			output_path=self.output_path,
			fpocket_path=self.fpocket_path,
			mgltools_path=self.mgltools_path,
			manual_center=self.manual_center,
			manual_npts=self.manual_npts,
		)

	def _ensure_prepared_inputs(self) -> None:
		"""Validate that preparation stages produced usable receptor and ligand files."""
		receptor_files = list_files_in_directory(self.prepared_receptor_path, ["*.pdbqt"])
		ligand_files = list_files_in_directory(self.prepared_ligand_path, ["*.pdbqt"])

		if not receptor_files:
			raise RuntimeError(
				f"No prepared receptor .pdbqt files found in {self.prepared_receptor_path}. "
				"Check the receptor input path and preparation logs."
			)

		if not ligand_files:
			raise RuntimeError(
				f"No prepared ligand .pdbqt files found in {self.prepared_ligand_path}. "
				"Check the ligand input path and preparation logs."
			)

	def run_receptor_preparation(self, n_workers: Optional[int] = None) -> Dict[str, int]:
		"""Prepare receptor inputs and convert them to PDBQT."""
		return self._build_receptor_preparation().prepare(n_workers=n_workers)

	def run_ligand_preparation(self, n_workers: Optional[int] = None) -> Dict[str, int]:
		"""Prepare ligand inputs and convert them to docking-ready files."""
		return self._build_ligand_preparation().prepare(n_workers=n_workers)

	def run_active_site_detection(self, n_workers: Optional[int] = None) -> Dict[str, int]:
		"""Detect binding pockets and generate GPF files."""
		return self._build_active_site_detection().prepare(n_workers=n_workers)

	def run_preparation_pipeline(
		self,
		receptor_workers: Optional[int] = None,
		ligand_workers: Optional[int] = None,
		active_site_workers: Optional[int] = None,
	) -> DockingPipelineResult:
		"""Run the preparation stages in order.

		The active-site stage consumes the prepared receptor and ligand directories
		generated by the first two stages.
		"""
		receptor_stats = self.run_receptor_preparation(n_workers=receptor_workers)
		ligand_stats = self.run_ligand_preparation(n_workers=ligand_workers)
		if receptor_stats.get("successful", 0) <= 0:
			raise RuntimeError(
				"Receptor preparation finished without successful outputs, so active-site detection cannot continue."
			)
		if ligand_stats.get("successful", 0) <= 0:
			raise RuntimeError(
				"Ligand preparation finished without successful outputs, so active-site detection cannot continue."
			)
		self._ensure_prepared_inputs()
		active_site_stats = self.run_active_site_detection(n_workers=active_site_workers)

		return DockingPipelineResult(
			receptor_preparation=receptor_stats,
			ligand_preparation=ligand_stats,
			active_site_detection=active_site_stats,
		)

	def run_full_pipeline(
		self,
		receptor_workers: Optional[int] = None,
		ligand_workers: Optional[int] = None,
		active_site_workers: Optional[int] = None,
		docking_workers: Optional[int] = None,
		autogrid_executable: Optional[str] = None,
		autodock_gpu_executable: Optional[str] = None,
		pdb_export_limit: int = 10,
	) -> DockingPipelineResult:
		"""Run preparation, docking execution, and analysis in sequence."""
		result = self.run_preparation_pipeline(
			receptor_workers=receptor_workers,
			ligand_workers=ligand_workers,
			active_site_workers=active_site_workers,
		)
		if result.active_site_detection.get("successful", 0) <= 0:
			raise RuntimeError(
				"Active-site detection did not generate outputs, so docking execution cannot continue."
			)
		docking_execution = self.run_docking_execution(
			n_workers=docking_workers,
			autogrid_executable=autogrid_executable,
			autodock_gpu_executable=autodock_gpu_executable,
		)
		docking_analysis = self.run_docking_analysis(pdb_export_limit=pdb_export_limit)
		result.docking_execution = docking_execution
		result.docking_analysis = docking_analysis
		return result

	def run_docking_execution(self, *args, **kwargs):
		"""Run the docking execution stage."""
		return DockingExecution(
			protein_maps_dir=self.prepared_receptor_path,
			ligand_dir=self.prepared_ligand_path,
			output_path=self.output_path,
			autogrid_executable=kwargs.pop("autogrid_executable", None),
			autodock_gpu_executable=kwargs.pop("autodock_gpu_executable", None),
		).run(*args, **kwargs)

	def run_docking_analysis(self, *args, **kwargs):
		"""Run the docking analysis stage."""
		return DockingAnalysis(
			output_path=self.output_path,
			pdb_export_limit=kwargs.pop("pdb_export_limit", 10),
		).run(*args, **kwargs)